In [1]:
import pandas as pd
import numpy as np

In [35]:
df = pd.read_csv("../AI_DS_SEM4_MASTER_RESULTS.csv")

In [36]:
df.head()

,student_id,seat_no,name,gender,status,ern,college,page,OE_code,OE_name,...,DT_credits,DT_gc,overall_total,maximum_total,percentage,result,remark,aC,aCG,sgpi
0,101410022,101410022,AARADHYA VISHAL SHINDE,MALE,Regular,MU0341120240205831,TERNA ENGINEERING COLLEGE NERUL NAVI MUMBAI,2,1313311,Administrative Policy of Chhatrapati Shivaji M...,...,2,16.0,549,775,70.84,UNSUCCESSFUL,FAILED,22,176.0,0.00000
1,101410023,101410023,ACHARI MOHIT PRABHAKARAN,MALE,Regular,NaN,TERNA ENGINEERING COLLEGE NERUL NAVI MUMBAI,3,1313311,Administrative Policy of Chhatrapati Shivaji M...,...,2,14.0,553,775,71.35,SUCCESSFUL,PASS,23,179.0,7.78261
2,101410024,101410024,ADINATH SOMNATH JAGTAP,MALE,Regular,MU0341120240205802,TERNA ENGINEERING COLLEGE NERUL NAVI MUMBAI,3,1313311,Administrative Policy of Chhatrapati Shivaji M...,...,2,20.0,616,775,79.48,SUCCESSFUL,PASS,23,196.0,8.52174
3,101410025,101410025,ANURAG SANTOSH AMALE,MALE,Regular,MU0341120240205785,TERNA ENGINEERING COLLEGE NERUL NAVI MUMBAI,4,1313311,Administrative Policy of Chhatrapati Shivaji M...,...,2,18.0,455,775,58.71,SUCCESSFUL,PASS,23,137.0,5.95652
4,101410026,101410026,ANVISHA VILAS ALKUTE,FEMALE,Regular,MU0341120240205844,TERNA ENGINEERING COLLEGE NERUL NAVI MUMBAI,4,1313311,Administrative Policy of Chhatrapati Shivaji M...,...,2,18.0,516,775,66.58,SUCCESSFUL,PASS,23,166.0,7.21739

In [37]:
df.tail()

,student_id,seat_no,name,gender,status,ern,college,page,OE_code,OE_name,...,DT_credits,DT_gc,overall_total,maximum_total,percentage,result,remark,aC,aCG,sgpi
83,101410948,101410948,SIDDHESH SANJAY PARDHI,MALE,Regular,MU0341120252010548,TERNA ENGINEERING COLLEGE NERUL NAVI MUMBAI,44,1313311,Administrative Policy of Chhatrapati Shivaji M...,...,2,14.0,329,775,42.45,UNSUCCESSFUL,FAILED,11,70.0,0.00000
84,101410949,101410949,ASHISH DINKAR THOMBARE,MALE,Regular,NaN,TERNA ENGINEERING COLLEGE NERUL NAVI MUMBAI,44,1313311,Administrative Policy of Chhatrapati Shivaji M...,...,2,14.0,429,775,55.35,SUCCESSFUL,PASS,23,126.0,5.47826
85,101410952,101410952,JAYESH VITTHAL BHOR,MALE,Regular,MU0341120252011274,TERNA ENGINEERING COLLEGE NERUL NAVI MUMBAI,45,1313311,Administrative Policy of Chhatrapati Shivaji M...,...,2,0.0,155,775,20.00,UNSUCCESSFUL,FAILED,0,0.0,0.00000
86,101410953,101410953,PRANAY PRAMOD MORE,MALE,Regular,MU0341120252011283,TERNA ENGINEERING COLLEGE NERUL NAVI MUMBAI,45,1313311,Administrative Policy of Chhatrapati Shivaji M...,...,2,14.0,227,775,29.29,UNSUCCESSFUL,FAILED,7,41.0,0.00000
87,101410954,101410954,SHREYA BHIMRAO KHARMATE,FEMALE,Regular,NaN,TERNA ENGINEERING COLLEGE NERUL NAVI MUMBAI,46,1313311,Administrative Policy of Chhatrapati Shivaji M...,...,2,0.0,220,775,28.39,UNSUCCESSFUL,FAILED,0,8.0,0.00000

In [76]:
#I noticed some missing ERN values so I have to find which ones are missing

missing = df.isnull().sum()
print(missing[missing > 0])

ern                   20
OE_internal            1
OE_total               1
CT_external            3
CT_internal            4
CT_total               1
DBMS_LAB_term_work     3
DBMS_LAB_total         3
OS_LAB_term_work       2
OS_LAB_oral            6
OS_LAB_total           4
FTS_external           1
FTS_internal           3
FTS_total              2
TC_LAB_term_work       5
TC_LAB_oral            5
dtype: int64

In [ ]:
print(df.loc[df["ern"].isnull(), "student_id"].to_list())

#I used this and pasted it in antigravity to extract the ern numbers from the pdf via the student_id so it can be automated

[101410023, 101410033, 101410034, 101410047, 101410048, 101410052, 101410053, 101410057, 101410061, 101410062, 101410067, 101410068, 101410071, 101410072, 101410078, 101410080, 101410088, 101410927, 101410949, 101410954]

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Columns: 113 entries, student_id to sgpi
dtypes: float64(29), int64(55), object(29)
memory usage: 77.8+ KB

In [39]:
df.shape

(88, 113)

In [48]:
col_list = df.columns.to_list()
print(col_list)

['student_id', 'seat_no', 'name', 'gender', 'status', 'ern', 'college', 'page', 'OE_code', 'OE_name', 'OE_external', 'OE_internal', 'OE_total', 'OE_grade', 'OE_gp', 'OE_credits', 'OE_gc', 'MINIPROJ_code', 'MINIPROJ_name', 'MINIPROJ_term_work', 'MINIPROJ_oral', 'MINIPROJ_total', 'MINIPROJ_grade', 'MINIPROJ_gp', 'MINIPROJ_credits', 'MINIPROJ_gc', 'CT_code', 'CT_name', 'CT_external', 'CT_internal', 'CT_total', 'CT_grade', 'CT_gp', 'CT_credits', 'CT_gc', 'DBMS_code', 'DBMS_name', 'DBMS_external', 'DBMS_internal', 'DBMS_total', 'DBMS_grade', 'DBMS_gp', 'DBMS_credits', 'DBMS_gc', 'OS_code', 'OS_name', 'OS_external', 'OS_internal', 'OS_total', 'OS_grade', 'OS_gp', 'OS_credits', 'OS_gc', 'DBMS_LAB_code', 'DBMS_LAB_name', 'DBMS_LAB_term_work', 'DBMS_LAB_oral', 'DBMS_LAB_total', 'DBMS_LAB_grade', 'DBMS_LAB_gp', 'DBMS_LAB_credits', 'DBMS_LAB_gc', 'OS_LAB_code', 'OS_LAB_name', 'OS_LAB_term_work', 'OS_LAB_oral', 'OS_LAB_total', 'OS_LAB_grade', 'OS_LAB_gp', 'OS_LAB_credits', 'OS_LAB_gc', 'FTS_code', 'FTS_name', 'FTS_external', 'FTS_internal', 'FTS_total', 'FTS_grade', 'FTS_gp', 'FTS_credits', 'FTS_gc', 'TC_LAB_code', 'TC_LAB_name', 'TC_LAB_term_work', 'TC_LAB_oral', 'TC_LAB_total', 'TC_LAB_grade', 'TC_LAB_gp', 'TC_LAB_credits', 'TC_LAB_gc', 'BMD_code', 'BMD_name', 'BMD_term_work', 'BMD_total', 'BMD_grade', 'BMD_gp', 'BMD_credits', 'BMD_gc', 'DT_code', 'DT_name', 'DT_term_work', 'DT_total', 'DT_grade', 'DT_gp', 'DT_credits', 'DT_gc', 'overall_total', 'maximum_total', 'percentage', 'result', 'remark', 'aC', 'aCG', 'sgpi']

In [42]:
df.describe()

,student_id,seat_no,page,OE_code,OE_external,OE_internal,OE_total,OE_gp,OE_credits,OE_gc,...,DT_total,DT_gp,DT_credits,DT_gc,overall_total,maximum_total,percentage,aC,aCG,sgpi
count,8.800000e+01,8.800000e+01,88.000000,88.0,88.000000,87.000000,87.000000,88.000000,88.0,88.000000,...,88.000000,88.000000,88.0,88.000000,88.000000,88.0,88.000000,88.000000,88.000000,88.000000
mean,1.014103e+08,1.014103e+08,24.000000,1313311.0,21.534091,14.597701,36.137931,7.500000,2.0,15.000000,...,34.954545,7.477273,2.0,14.954545,480.056818,775.0,61.942500,19.852273,142.863636,5.041501
std,3.798775e+02,3.798775e+02,12.781092,0.0,4.598723,3.408129,6.737905,2.202402,0.0,4.404804,...,11.958654,2.812032,0.0,5.624064,124.522016,0.0,16.067066,6.305516,53.426753,3.619075
min,1.014100e+08,1.014100e+08,2.000000,1313311.0,0.000000,0.000000,19.000000,0.000000,2.0,0.000000,...,0.000000,0.000000,2.0,0.000000,22.000000,775.0,2.840000,0.000000,0.000000,0.000000
25%,1.014100e+08,1.014100e+08,13.000000,1313311.0,18.750000,13.000000,31.000000,7.000000,2.0,14.000000,...,34.000000,7.000000,2.0,14.000000,398.750000,775.0,51.450000,20.000000,111.000000,0.000000
50%,1.014101e+08,1.014101e+08,24.000000,1313311.0,22.000000,15.000000,38.000000,8.000000,2.0,16.000000,...,39.500000,8.500000,2.0,17.000000,517.500000,775.0,66.775000,23.000000,165.000000,7.130430
75%,1.014101e+08,1.014101e+08,35.000000,1313311.0,25.000000,17.000000,41.000000,9.000000,2.0,18.000000,...,42.000000,9.000000,2.0,18.000000,567.000000,775.0,73.160000,23.000000,180.500000,7.793480
max,1.014110e+08,1.014110e+08,46.000000,1313311.0,28.000000,20.000000,47.000000,10.000000,2.0,20.000000,...,45.000000,10.000000,2.0,20.000000,663.000000,775.0,85.550000,23.000000,210.000000,9.130430

In [63]:
print(df["gender"].value_counts())
print(df["sgpi"].value_counts())

gender
MALE      60
FEMALE    28
Name: count, dtype: int64
sgpi
0.00000    29
7.78261     3
7.17391     3
7.43478     3
8.30435     3
7.13043     2
7.65217     2
7.73913     2
8.13043     2
7.39130     2
7.00000     2
6.56522     2
7.34783     2
7.82609     1
8.52174     1
5.95652     1
7.21739     1
8.17391     1
7.91304     1
6.43478     1
8.34783     1
6.39130     1
6.60870     1
7.26087     1
6.78261     1
8.21739     1
8.69565     1
6.26087     1
8.26087     1
6.65217     1
8.73913     1
7.95652     1
9.13043     1
8.08696     1
7.52174     1
8.56522     1
8.39130     1
8.00000     1
8.86957     1
7.30435     1
5.78261     1
5.65217     1
8.65217     1
5.47826     1
Name: count, dtype: int64